version: "3.8"
services:
  db:
    image: postgres:15
    container_name: hw-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hw-db
    ports:
      - "5432:5432"
    volumes:
      - hw-db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: hw-cash
    restart: always
    ports:
      - "6379:6379"

volumes:
  hw-db-data: